# Generated by Django 2.2.6 on 2019-11-05 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body1', models.TextField()),
                ('body2', models.TextField()),
                ('body3', models.TextField()),
                ('body4', models.TextField()),
                ('body5', models.TextField()),
                ('body6', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
